python process.py \
    --input ./examples \
    --output ./output \
    --sd_path ./weights/yoso-delight-v0-4-base \
    --duck_path ./weights/Duck16mod_Spec_99_new.pt \
    --lama_path ./weights/big-lama \
    --lama_dilate_size 15 \
    --mix_thresh 150 \
    # --disable_sd \
